---
- name: Simple debug play
  hosts: all
  vars:
    - message: "Hello world!"
  tasks:
    - name: Print a debug message
      debug:
        msg: "{{ message }}"

    - name: Pause number 01
      pause:
        minutes: 2

    - name: Pause number 02
      pause:
        minutes: 2

