---
- name: Simple debug play
  hosts: all
  vars:
    - message: "Hello world!"
  tasks:
    - name: Print a debug message
      debug:
        msg: "{{ message }}"

    - name: Print the manageiq variable
      debug:
        var: manageiq
      when: manageiq is defined
